=== omunroe-com/ubtvlc/modules/gui/skins/parser/skin.dtd
<!--
 *****************************************************************************
 * skin.dtd: DTD for the VLC skins
 *****************************************************************************
 * Copyright (C) 2003 VideoLAN
 * $Id: skin.dtd 6961 2004-03-05 17:34:23Z sam $
 *
 * Authors: Olivier Teulière <ipkiss@via.ecp.fr>
 *          Emmanuel Puig    <karibu@via.ecp.fr>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111,
 * USA.
 *****************************************************************************
-->


<!ELEMENT Theme (ThemeInfo,(Bitmap|Font|Window|Event)*)>
    <!ATTLIST Theme
        magnet      CDATA   "9"
    >

<!-- main elements -->
<!ELEMENT Bitmap EMPTY>
    <!ATTLIST Bitmap
        id          CDATA   #REQUIRED
        file        CDATA   #REQUIRED
        alphacolor  CDATA   #REQUIRED
    >
<!ELEMENT Event EMPTY>
    <!ATTLIST Event
        id          CDATA   #REQUIRED
        event       CDATA   #REQUIRED
        key         CDATA   "none"
    >
<!ELEMENT Font EMPTY>
    <!ATTLIST Font
        id          CDATA   "default"
        font        CDATA   "arial"
        size        CDATA   "12"
        color       CDATA   "#000000"
        weight      CDATA   "400"
        italic      CDATA   "false"
        underline   CDATA   "false"
    >
<!ELEMENT ThemeInfo EMPTY>
    <!ATTLIST ThemeInfo
        name        CDATA   #IMPLIED
        author      CDATA   #IMPLIED
        email       CDATA   #IMPLIED
        webpage     CDATA   #IMPLIED
    >
<!ELEMENT Window (ControlGroup)>
    <!ATTLIST Window
        id          CDATA   #REQUIRED
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        fadetime    CDATA   "500"
        alpha       CDATA   "255"
        movealpha   CDATA   "255"
        dragdrop    CDATA   "true"
        playondrop  CDATA   "true"
    >

<!ELEMENT ControlGroup (ControlGroup|ImageControl|ButtonControl|PlayListControl|
                        SliderControl|TextControl|CheckBoxControl|
                        RectangleControl|Anchor)+>
    <!ATTLIST ControlGroup
        x           CDATA   "\0"
        y           CDATA   "\0"
    >

<!-- Anchors -->
<!ELEMENT Anchor EMPTY>
    <!ATTLIST Anchor
        x           CDATA   "\0"
        y           CDATA   "\0"
        priority    CDATA   #REQUIRED
        range       CDATA   "10"
    >

<!-- Controls -->
<!ELEMENT ImageControl EMPTY>
    <!ATTLIST ImageControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        image       CDATA   #REQUIRED
        onclick     CDATA   "none"
        help        CDATA   "\0"
    >
<!ELEMENT RectangleControl EMPTY>
    <!ATTLIST RectangleControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        w           CDATA   "50"
        h           CDATA   "50"
        color       CDATA   "#C0C0C0"
        onclick     CDATA   "none"
        help        CDATA   "\0"
    >
<!ELEMENT ButtonControl EMPTY>
    <!ATTLIST ButtonControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        up          CDATA   #REQUIRED
        down        CDATA   #REQUIRED
        disabled    CDATA   "none"
        onclick     CDATA   "none"
        onmouseover CDATA   "none"
        onmouseout  CDATA   "none"
        tooltiptext CDATA   "none"
        help        CDATA   "\0"
    >
<!ELEMENT CheckBoxControl EMPTY>
    <!ATTLIST CheckBoxControl
        id           CDATA   "none"
        visible      CDATA   "true"
        x            CDATA   "\0"
        y            CDATA   "\0"
        img1         CDATA   #REQUIRED
        clickimg1    CDATA   "none"
        img2         CDATA   #REQUIRED
        clickimg2    CDATA   "none"
        disabled1    CDATA   "none"
        disabled2    CDATA   "none"
        onclick1     CDATA   "none"
        onclick2     CDATA   "none"
        onmouseover1 CDATA   "none"
        onmouseout1  CDATA   "none"
        onmouseover2 CDATA   "none"
        onmouseout2  CDATA   "none"
        tooltiptext1 CDATA   "none"
        tooltiptext2 CDATA   "none"
        help         CDATA   "\0"
    >
<!ELEMENT SliderControl EMPTY>
    <!ATTLIST SliderControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        type        CDATA   "time"
        up          CDATA   #REQUIRED
        down        CDATA   #REQUIRED
        abs         CDATA   #REQUIRED
        ord         CDATA   #REQUIRED
        tooltiptext CDATA   "none"
        help        CDATA   "\0"
    >
<!ELEMENT TextControl EMPTY>
    <!ATTLIST TextControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        text        CDATA   ""
        font        CDATA   #REQUIRED
        align       CDATA   "left"
        width       CDATA   "\0"
        display     CDATA   "none"
        scroll      CDATA   "true"
        scrollspace CDATA   "20"
        help        CDATA   "\0"
    >
<!ELEMENT PlayListControl SliderControl>
    <!ATTLIST PlayListControl
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "\0"
        y           CDATA   "\0"
        width       CDATA   "200"
        infowidth   CDATA   "50"
        font        CDATA   #REQUIRED
        playfont    CDATA   "none"
        selcolor    CDATA   "#0000FF"
        abs         CDATA   #REQUIRED
        ord         CDATA   #REQUIRED
        help        CDATA   "\0"
        longfilename CDATA   "false"
    >

=== omunroe-com/ubtvlc/share/skins/default/theme.xml
<!DOCTYPE Theme SYSTEM "skin.dtd">

<Theme>
    <ThemeInfo name="VLC" author="Emmanuel Puig"
            email="magic@karibu.org" webpage=""/>

  <Bitmap id="body" file="body.bmp" alphacolor="#FF0000"/>

  <Bitmap id="prev1" file="prev1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="prev2" file="prev2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="prev3" file="prev3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="prev4" file="prev4.bmp" alphacolor="#FF0000"/>
  <Bitmap id="stop1" file="stop1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="stop2" file="stop2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="stop3" file="stop3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="stop4" file="stop4.bmp" alphacolor="#FF0000"/>
  <Bitmap id="play1" file="play1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="play2" file="play2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="play3" file="play3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="play4" file="play4.bmp" alphacolor="#FF0000"/>
  <Bitmap id="pause1" file="pause1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="pause2" file="pause2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="pause3" file="pause3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="pause4" file="pause4.bmp" alphacolor="#FF0000"/>
  <Bitmap id="next1" file="next1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="next2" file="next2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="next3" file="next3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="next4" file="next4.bmp" alphacolor="#FF0000"/>
  <Bitmap id="playlist1" file="playlist1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="playlist2" file="playlist2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="playlist3" file="playlist3.bmp" alphacolor="#FF0000"/>

  <Bitmap id="quit1" file="quit1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="quit2" file="quit2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="quit3" file="quit3.bmp" alphacolor="#FF0000"/>

  <Bitmap id="slider1" file="slider1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="slider2" file="slider2.bmp" alphacolor="#FF0000"/>

  <Bitmap id="playlist_body" file="playlist_body.bmp" alphacolor="#FF0000"/>

  <Bitmap id="open1" file="open1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="open2" file="open2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="open3" file="open3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="add1" file="add1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="add2" file="add2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="add3" file="add3.bmp" alphacolor="#FF0000"/>
  <Bitmap id="del1" file="del1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="del2" file="del2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="del3" file="del3.bmp" alphacolor="#FF0000"/> 
  <Bitmap id="prefs1" file="prefs1.bmp" alphacolor="#FF0000"/>
  <Bitmap id="prefs2" file="prefs2.bmp" alphacolor="#FF0000"/>
  <Bitmap id="prefs3" file="prefs3.bmp" alphacolor="#FF0000"/>

  <Event id="hide1" event="CTRL_ID_VISIBLE(img1,FALSE)"/>
  <Event id="hide2" event="CTRL_ID_VISIBLE(img2,FALSE)"/>
  <Event id="hide3" event="CTRL_ID_VISIBLE(img3,FALSE)"/>
  <Event id="hide4" event="CTRL_ID_VISIBLE(img4,FALSE)"/>
  <Event id="hide5" event="CTRL_ID_VISIBLE(img5,FALSE)"/>
  <Event id="hide6" event="CTRL_ID_VISIBLE(img6,FALSE)"/>
  <Event id="hideQ" event="CTRL_ID_VISIBLE(imgQ,FALSE)"/>

  <Event id="show1" event="CTRL_ID_VISIBLE(img1,TRUE)"/>
  <Event id="show2" event="CTRL_ID_VISIBLE(img2,TRUE)"/>
  <Event id="show3" event="CTRL_ID_VISIBLE(img3,TRUE)"/>
  <Event id="show4" event="CTRL_ID_VISIBLE(img4,TRUE)"/>
  <Event id="show5" event="CTRL_ID_VISIBLE(img5,TRUE)"/>
  <Event id="show6" event="CTRL_ID_VISIBLE(img6,TRUE)"/>
  <Event id="showQ" event="CTRL_ID_VISIBLE(imgQ,TRUE)"/>
  <Event id="showP" event="WINDOW_OPEN(PlaylistWindow)"/>
  <Event id="hideP" event="WINDOW_CLOSE(PlaylistWindow)"/>

  <Event id="hideOpen" event="CTRL_ID_VISIBLE(Open,FALSE)"/>
  <Event id="hideAdd"  event="CTRL_ID_VISIBLE(Add,FALSE)"/>
  <Event id="hideDel"  event="CTRL_ID_VISIBLE(Del,FALSE)"/>
  <Event id="hidePrefs"  event="CTRL_ID_VISIBLE(Prefs,FALSE)"/>

  <Event id="showOpen" event="CTRL_ID_VISIBLE(Open,TRUE)"/>
  <Event id="showAdd"  event="CTRL_ID_VISIBLE(Add,TRUE)"/>
  <Event id="showDel"  event="CTRL_ID_VISIBLE(Del,TRUE)"/>
  <Event id="showPrefs"  event="CTRL_ID_VISIBLE(Prefs,TRUE)"/>

  <Event id="MoveWindow" event="WINDOW_MOVE(Window)"/>
  <Event id="MovePlaylist" event="WINDOW_MOVE(PlaylistWindow)"/>

  <Event id="Del" event="PLAYLIST_ID_DEL(playlist)"/>

  <Font id="fnt" font="arial" size="8" weight="600" color="#000000"/>
  <Font id="vlc1" font="arial" size="8" weight="600" color="#000000"/>
  <Font id="vlc2" font="arial" size="8" weight="600" color="#C0C0C0"/>

  <Font id="playlist1" font="arial" size="8" color="#000000" weight="200"/>
  <Font id="playlist2" font="arial" size="8" color="#FF0000" weight="200"/>

  <Window id="Window" x="200" y="100" alpha="255" fadetime="500" movealpha="192">
    <ControlGroup x="0" y="0">
      <Anchor x="0" y="105" priority="100"/>
      <ImageControl x="0" y="0" image="body" onclick="MoveWindow"/>
      <TextControl font="vlc2" x="24" y="6" width="150" text="VLC Media Player Skin"/>
      <TextControl font="vlc1" x="23" y="5" width="150" text="VLC Media Player Skin"/>

      <ControlGroup x="14" y="73">
        <ImageControl id="img1" x="0"   y="0" image="prev4"  visible="false"/>
        <ImageControl id="img2" x="26"  y="0" image="stop4"  visible="false"/>
        <ImageControl id="img3" x="52"  y="0" image="play4"  visible="false"/>
        <ImageControl id="img4" x="78"  y="0" image="pause4" visible="false"/>
        <ImageControl id="img5" x="104" y="0" image="next4"  visible="false"/>
        <ImageControl id="img6" x="130" y="0" image="playlist3" visible="false"/>
        <ButtonControl x="3"   y="3" up="prev1"  down="prev2"  disabled="prev3"  onclick="prev"  onmouseover="show1" onmouseout="hide1" tooltiptext="Previous file"/>
        <ButtonControl x="29"  y="3" up="stop1"  down="stop2"  disabled="stop3"  onclick="stop"  onmouseover="show2" onmouseout="hide2" tooltiptext="Stop"/>
        <ButtonControl x="55"  y="3" up="play1"  down="play2"  disabled="play3"  onclick="play"  onmouseover="show3" onmouseout="hide3" tooltiptext="Play"/>
        <ButtonControl x="81"  y="3" up="pause1" down="pause2" disabled="pause3" onclick="pause" onmouseover="show4" onmouseout="hide4" tooltiptext="Pause"/>
        <ButtonControl x="107" y="3" up="next1"  down="next2"  disabled="next3"  onclick="next"  onmouseover="show5" onmouseout="hide5" tooltiptext="Next file"/>
        <CheckBoxControl x="133" y="3" img1="playlist1" img2="playlist2" onclick1="showP" onclick2="hideP" onmouseover1="show6" onmouseout1="hide6" tooltiptext1="Show playlist" tooltiptext2="Hide playlist"/>
      </ControlGroup>
      <ControlGroup x="4" y="4">
        <ImageControl id="imgQ" x="0" y="0" image="quit3" visible="false"/>
        <ButtonControl x="1" y="1" up="quit1" down="quit2" onclick="quit" onmouseover="showQ" onmouseout="hideQ" tooltiptext="Quit"/>
      </ControlGroup>

      <ControlGroup x="183" y="12">
        <SliderControl up="slider1" down="slider2" abs="0,0" ord="68,0" tooltiptext="Time"/>
        <SliderControl x="17" type="volume" up="slider1" down="slider2" abs="0,0" ord="68,0" tooltiptext="Sound"/>
      </ControlGroup>

      <ControlGroup x="18" y="24">
        <TextControl font="fnt" align="left" x="0" y="0" width="148" text=" " display="file_name"/>
        <TextControl font="fnt" align="right" x="71"  y="22" width="69" text=" " display="time;left_time"/>
        <TextControl font="fnt" align="right" x="148" y="22" width="69" text=" " display="total_time"/>
      </ControlGroup>

    </ControlGroup>
  </Window>

  <Window id="PlaylistWindow" x="200" y="205" visible="false" alpha="255" fadetime="500" movealpha="192" playondrop="false">
    <ControlGroup x="0" y="0">
      <Anchor x="0" y="0" priority="50"/>
      <ImageControl x="0" y="0" image="playlist_body" onclick="MovePlaylist"/>
      <ControlGroup x="14" y="4">
        <ImageControl id="Open" x="0"  y="0" image="open3" visible="false"/>
        <ImageControl id="Add"  x="26" y="0" image="add3"  visible="false"/>
        <ImageControl id="Del"  x="52" y="0" image="del3"  visible="false"/>
        <ImageControl id="Prefs"  x="78" y="0" image="prefs3"  visible="false"/>
        <ButtonControl x="3"   y="3" up="open1" down="open2" onclick="open" onmouseover="showOpen" onmouseout="hideOpen" tooltiptext="Open a file"/>
        <ButtonControl x="29"  y="3" up="add1"  down="add2"  onclick="add_file" onmouseover="showAdd"  onmouseout="hideAdd"  tooltiptext="Add files"/>
        <ButtonControl x="55"  y="3" up="del1"  down="del2"  onclick="Del" onmouseover="showDel"  onmouseout="hideDel"  tooltiptext="Remove items"/>
        <ButtonControl x="81"  y="3" up="prefs1"  down="prefs2"  onclick="show_prefs" onmouseover="showPrefs"  onmouseout="hidePrefs"  tooltiptext="Show preferences"/>
      </ControlGroup>
      <PlayListControl id="playlist" width="180" selcolor="#C0D0E0" font="playlist1" playfont="playlist2" abs="9,9" ord="35,150">
        <SliderControl x="201" up="slider1" down="slider2" abs="0,0" ord="36,149"/>
      </PlayListControl>

    </ControlGroup>
  </Window>

</Theme>
