=== omunroe-com/ubtvlc/share/skins2/skin.dtd
<!-- version 2.0
-->


<!ELEMENT Theme (ThemeInfo,(Bitmap|BitmapFont|Font|Window)*)>
    <!ATTLIST Theme
        version     CDATA   #REQUIRED
        tooltipfont CDATA   "defaultfont"
        magnet      CDATA   "15"
        alpha       CDATA   "255"
        movealpha   CDATA   "255"
    >

<!-- main elements -->
<!ELEMENT Bitmap EMPTY>
    <!ATTLIST Bitmap
        id          CDATA   #REQUIRED
        file        CDATA   #REQUIRED
        alphacolor  CDATA   #REQUIRED
    >
<!ELEMENT Font EMPTY>
    <!ATTLIST Font
        id          CDATA   #REQUIRED
        file        CDATA   #REQUIRED
        size        CDATA   "12"
    >
<!ELEMENT BitmapFont EMPTY>
    <!ATTLIST BitmapFont
        id          CDATA   #REQUIRED
        file        CDATA   #REQUIRED
        type        CDATA   "digits"
    >
<!ELEMENT ThemeInfo EMPTY>
    <!ATTLIST ThemeInfo
        name        CDATA   #IMPLIED
        author      CDATA   #IMPLIED
        email       CDATA   #IMPLIED
        webpage     CDATA   #IMPLIED
    >
<!ELEMENT Window (Layout)+>
    <!ATTLIST Window
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        dragdrop    CDATA   "true"
        playondrop  CDATA   "true"
    >

<!ELEMENT Layout (Group)>
    <!ATTLIST Layout
        id          CDATA   "none"
        width       CDATA   #REQUIRED
        height      CDATA   #REQUIRED
        minwidth    CDATA   "-1"
        maxwidth    CDATA   "-1"
        minheight   CDATA   "-1"
        maxheight   CDATA   "-1"
    >
<!ELEMENT Group (Group|Image|Button|Playlist|Slider|RadialSlider|Text|Checkbox|
                 Anchor|Video)+>
    <!ATTLIST Group
        x           CDATA   "0"
        y           CDATA   "0"
    >

<!-- Anchors -->
<!ELEMENT Anchor EMPTY>
    <!ATTLIST Anchor
        x           CDATA   "0"
        y           CDATA   "0"
        priority    CDATA   #REQUIRED
        points      CDATA   "(0,0)"
        range       CDATA   "10"
    >

<!-- Controls -->
<!ELEMENT Image EMPTY>
    <!ATTLIST Image
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        image       CDATA   #REQUIRED
        action      CDATA   "none"
        help        CDATA   ""
    >
<!ELEMENT Button EMPTY>
    <!ATTLIST Button
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        up          CDATA   #REQUIRED
        down        CDATA   "none"
        over        CDATA   "none"
        action      CDATA   "none"
        tooltiptext CDATA   ""
        help        CDATA   ""
    >
<!ELEMENT Checkbox EMPTY>
    <!ATTLIST Checkbox
        id           CDATA   "none"
        visible      CDATA   "true"
        x            CDATA   "0"
        y            CDATA   "0"
        lefttop      CDATA   "lefttop"
        rightbottom  CDATA   "lefttop"
        up1          CDATA   #REQUIRED
        down1        CDATA   "none"
        over1        CDATA   "none"
        up2          CDATA   #REQUIRED
        down2        CDATA   "none"
        over2        CDATA   "none"
        state        CDATA   #REQUIRED
        action1      CDATA   "none"
        action2      CDATA   "none"
        tooltiptext1 CDATA   ""
        tooltiptext2 CDATA   ""
        help         CDATA   ""
    >
<!ELEMENT Slider EMPTY>
    <!ATTLIST Slider
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        up          CDATA   #REQUIRED
        down        CDATA   "none"
        over        CDATA   "none"
        points      CDATA   #REQUIRED
        thickness   CDATA   "10"
        value       CDATA   "none"
        tooltiptext CDATA   ""
        help        CDATA   ""
    >
<!ELEMENT RadialSlider EMPTY>
    <!ATTLIST RadialSlider
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        sequence    CDATA   #REQUIRED
        nbimages    CDATA   #REQUIRED
        minangle    CDATA   "0"
        maxangle    CDATA   "360"
        value       CDATA   "none"
        tooltiptext CDATA   ""
        help        CDATA   ""
    >
<!ELEMENT Text EMPTY>
    <!ATTLIST Text
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        text        CDATA   ""
        font        CDATA   #REQUIRED
        color       CDATA   "#000000"
        width       CDATA   "0"
        help        CDATA   ""
    >
<!ELEMENT Playlist (Slider)?>
    <!ATTLIST Playlist
        id          CDATA   #REQUIRED
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        width       CDATA   "0"
        height      CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        font        CDATA   #REQUIRED
        fgcolor     CDATA   "#000000"
        playcolor   CDATA   "#FF0000"
        bgcolor1    CDATA   "#FFFFFF"
        bgcolor2    CDATA   "#FFFFFF"
        selcolor    CDATA   "#0000FF"
        help        CDATA   ""
    >
<!ELEMENT Video EMPTY>
    <!ATTLIST Video
        id          CDATA   "none"
        visible     CDATA   "true"
        x           CDATA   "0"
        y           CDATA   "0"
        width       CDATA   "0"
        height      CDATA   "0"
        lefttop     CDATA   "lefttop"
        rightbottom CDATA   "lefttop"
        help        CDATA   ""
    >

=== omunroe-com/ubtvlc/share/skins2/default/theme.xml
<!DOCTYPE Theme PUBLIC "-//VideoLAN//DTD VLC Skins V2.0//EN" "skin.dtd">

<Theme version="2.0" magnet="20" alpha="255" movealpha="192">
  <ThemeInfo name="VLC OSX Interface" author="BigBen"
             email="bigben@videolan.org" webpage="http://www.videolan.org"/>

  <Bitmap id="mainbody" file="body.png" alphacolor="#FF0000"/>

  <Bitmap id="add_item" file="add_item.png" alphacolor="#FF0000"/>
  <Bitmap id="add_item_onclick" file="add_item_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="close" file="close.png" alphacolor="#00FF00"/>
  <Bitmap id="close_onclick" file="close_onclick.png" alphacolor="#00FF00"/>
  <Bitmap id="close_mouseover" file="close_mouseover.png" alphacolor="#00FF00"/>
  <Bitmap id="delete_item" file="delete_item.png" alphacolor="#FF0000"/>
  <Bitmap id="delete_item_onclick" file="delete_item_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="fast" file="fast.png" alphacolor="#FF0000"/>
  <Bitmap id="fast_click" file="fast_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="fast_disabled" file="fast_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="rev" file="rev.png" alphacolor="#FF0000"/>
  <Bitmap id="rev_click" file="rev_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="next" file="next.png" alphacolor="#FF0000"/>
  <Bitmap id="next_disabled" file="next_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="next_onclick" file="next_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="pause" file="pause.png" alphacolor="#FF0000"/>
  <Bitmap id="pause_onclick" file="pause_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="play" file="play.png" alphacolor="#FF0000"/>
  <Bitmap id="play_onclick" file="play_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="disabled" file="disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist1" file="playlist_body1.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist2" file="playlist_body2.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist3" file="playlist_body3.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist4" file="playlist_body4.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist6" file="playlist_body6.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist7" file="playlist_body7.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist8" file="playlist_body8.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist9" file="playlist_body9.png" alphacolor="#FF0000"/>
  <Bitmap id="resize" file="resize.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist_button" file="playlist_button.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist_button_onclick" file="playlist_button_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist_button2" file="playlist_button2.png" alphacolor="#FF0000"/>
  <Bitmap id="playlist_button_onclick2" file="playlist_button_onclick2.png" alphacolor="#FF0000"/>
  <Bitmap id="sort_button" file="sort.png" alphacolor="#FF0000"/>
  <Bitmap id="sort_button_onclick" file="sort_onclick.png" alphacolor="#FF0000"/>
<!--
  <Bitmap id="voutbody1" file="vout_top_left.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody2" file="vout_top.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody3" file="vout_top_right.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody4" file="vout_left.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody6" file="vout_right.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody7" file="vout_bottom_left.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody8" file="vout_bottom.png" alphacolor="#FF0000"/>
  <Bitmap id="voutbody9" file="vout_bottom_right.png" alphacolor="#FF0000"/>
  <Bitmap id="vout_button" file="vout.png" alphacolor="#FF0000"/>
  <Bitmap id="vout_button_onclick" file="vout_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="vout_button2" file="vout2.png" alphacolor="#FF0000"/>
  <Bitmap id="vout_button_onclick2" file="vout_onclick.png" alphacolor="#FF0000"/>
-->
  <Bitmap id="preferences" file="preferences.png" alphacolor="#FF0000"/>
  <Bitmap id="preferences_onclick" file="preferences_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="previous" file="previous.png" alphacolor="#FF0000"/>
  <Bitmap id="previous_disabled" file="previous_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="previous_onclick" file="previous_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="reduce" file="reduce.png" alphacolor="#FF0000"/>
  <Bitmap id="reduce_onclick" file="reduce_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="reduce_disabled" file="reduce_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="slider" file="slider.png" alphacolor="#FF0000"/>
  <Bitmap id="slider_onclick" file="slider_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="slider_playlist" file="slider_playlist.png" alphacolor="#FF0000"/>
  <Bitmap id="slider_volume" file="slider_volume.png" alphacolor="#FF0000"/>
  <Bitmap id="slider_volume_onclick" file="slider_volume_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="slow" file="slow.png" alphacolor="#FF0000"/>
  <Bitmap id="slow_disabled" file="slow_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="slow_onclick" file="slow_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="stop" file="stop.png" alphacolor="#FF0000"/>
  <Bitmap id="stop_disabled" file="stop_disabled.png" alphacolor="#FF0000"/>
  <Bitmap id="stop_onclick" file="stop_onclick.png" alphacolor="#FF0000"/>
  <Bitmap id="volume_radial" file="volume.png" alphacolor="#FF0000"/>

  <Font id="default_font" file="FreeSansBold.ttf" size="15"/>
  <Font id="playlist_font" file="FreeSansBold.ttf" size="12"/>

  <Window x="230" y="250" dragdrop="true">

   <Layout id="mainlayout" width="424" height="152">
    <Group x="0" y="0">
      <Anchor x="7" y="151" points="(0,0)" priority="100"/>
      <Image x="0" y="0" image="mainbody" action="move"/>
      <Text font="default_font" width="70" x="287" y="79" text="$T" color="#000000"/>
      <Button x="42" y="42" up="preferences" down="preferences_onclick" over="preferences" action="dialogs.prefs()" tooltiptext="Preferences"/>
      <Button x="17" y="64" up="stop" down="stop_onclick" over="stop" action="vlc.stop()" tooltiptext="Stop"/>
      <Checkbox x="42" y="87" up1="playlist_button" down1="playlist_button_onclick" up2="playlist_button2" down2="playlist_button_onclick2" state="playlist_window.isVisible" action1="playlist_window.show()" action2="playlist_window.hide()" tooltiptext1="Show Playlist" tooltiptext2="Hide Playlist"/>
      <Checkbox x="83" y="44" up1="play" up2="pause" down1="play_onclick" down2="pause_onclick" state="vlc.isPlaying" action1="vlc.play()" action2="vlc.pause()" tooltiptext1="Play" tooltiptext2="Pause"/>
      <Button x="159" y="37" up="rev" down="rev_click" over="rev" action="vlc.slower()" tooltiptext="Slower"/>
      <Button x="159" y="89" up="fast" down="fast_click" over="fast" action="vlc.faster()" tooltiptext="Faster"/>
      <Button x="196" y="46" up="previous" down="previous_onclick" over="previous" action="playlist.previous()" tooltiptext="Previous Item"/>
      <Button x="196" y="79" up="next" down="next_onclick" over="next" action="playlist.next()" tooltiptext="Next Item"/>
      <Button x="8" y="5" up="close" down="close_onclick" over="close_mouseover" action="vlc.quit()" tooltiptext="Quit VLC" help="quit"/>
      <Image x="29" y="5" image="reduce_disabled"/>
      <Slider id="time_slider" x="24" y="130" up="slider" down="slider_onclick" points="(0,0),(366,0)" value="time" visible="vlc.isSeekable and not vlc.isStopped" tooltiptext="Time: $T"/>
      <Slider id="volume_slider" x="391" y="53" up="slider_volume" down="slider_volume_onclick" points="(0,47),(0,0)" value="volume" tooltiptext="Volume: $V%"/>
    </Group>
   </Layout>
  </Window>
  <Window id="playlist_window" x="237" y="401" visible="false">
   <Layout id="playlistLayout" width="410" height="250" minwidth="200" minheight="150" maxwidth="1000" maxheight="800">
    <Group x="0" y="0">
      <Anchor x="0" y="0" points="(0,0)" priority="50"/>
      <Image image="playlist1" x="0" y="0" lefttop="lefttop" rightbottom="lefttop" action="move"/>
      <Image image="playlist2" x="17" y="0" lefttop="lefttop" rightbottom="righttop" action="move"/>
      <Image image="playlist3" x="350" y="0" lefttop="righttop" rightbottom="righttop" action="move"/>
      <Image image="playlist4" x="0" y="70" lefttop="lefttop" rightbottom="leftbottom" action="move"/>
      <Image image="playlist6" x="350" y="70" lefttop="righttop" rightbottom="rightbottom" action="move"/>
      <Image image="playlist7" x="0" y="200" lefttop="leftbottom" rightbottom="leftbottom" action="move"/>
      <Image image="playlist8" x="17" y="200" lefttop="leftbottom" rightbottom="rightbottom" action="move"/>
      <Image image="playlist9" x="350" y="200" lefttop="rightbottom" rightbottom="rightbottom" action="move"/> 
      <Image image="resize" x="392" y="232" lefttop="rightbottom" rightbottom="rightbottom" action="resizeSE"/>

      <Button x="374" y="12" lefttop="righttop" rightbottom="righttop" up="add_item" down="add_item_onclick" over="add_item" action="playlist.add()" tooltiptext="Add item"/>
      <Button x="374" y="40" up="delete_item" lefttop="righttop" rightbottom="righttop" down="delete_item_onclick" over="delete_item" action="playlist.del()" tooltiptext="Del item"/>
      <Button x="374" y="68" up="sort_button" lefttop="righttop" rightbottom="righttop" down="sort_button_onclick" over="sort_button" action="playlist.sort()" tooltiptext="Sort the playlist"/>
  <!-- <Checkbox x="374" y="96" up1="vout_button" lefttop="righttop" rightbottom="righttop" down1="vout_button_onclick" up2="vout_button2" down2="vout_button_onclick2" state="vout_window.isVisible" action1="vout_window.show()" action2="vout_window.hide()" tooltiptext1="Show Video Window" tooltiptext2="Hide Video Window"/> -->
      <Playlist id="playlist" x="17" y="15" width="333" height="204" lefttop="lefttop" rightbottom="rightbottom" font="playlist_font" fgcolor="#000000" playcolor="#ff0000" bgcolor1="#ffffff" bgcolor2="#e0e0ff" selcolor="#4e8bc7">
